services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-cli
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1